//! Component state and utilities for the static text editor.
//!
//! This module defines the state struct that holds the editor's runtime data
//! (text, undo/redo history, DOM refs, template model, and PDF viewer state),
//! along with small helper methods used by the view and update logic.
//!
//! The inline documentation describes each public field and the contract of
//! the `resize_textarea` helper.

use wasm_bindgen::JsCast;
use web_sys::{HtmlElement, HtmlTextAreaElement};
use yew::prelude::*;

use common::model::template::Template;

/// Main state container for the `StaticTextComponent`.
///
/// Holds all runtime data for the editor. Fields are public to be accessed
/// directly by the `view` and `update` modules, following an Elm-like pattern.
pub struct StaticTextComponent {
    /// The current UTF-8 string content of the `<textarea>`. This is the single
    /// source of truth for the text being edited. It is updated by `Msg::UpdateText`.
    pub text: String,

    /// A stack of text snapshots used for the undo/redo functionality. A new entry
    /// is pushed on `Msg::UpdateText`. `Msg::Undo` and `Msg::Redo` navigate this stack.
    pub history: Vec<String>,

    /// The current position within the `history` stack. Points to the version of
    /// the text currently displayed in the editor.
    pub history_index: usize,

    /// A string identifier for the currently visible tab, either `"editor"` or `"preview"`.
    /// Used by `view.rs` to conditionally render the correct UI.
    pub active_tab: String,

    /// A reference to the `<textarea>` DOM element. Used for programmatic actions like
    /// resizing (`resize_textarea`), focusing, and getting/setting selection ranges.
    pub textarea_ref: NodeRef,

    /// A reference to the hidden `<input type="file">` element. This is triggered
    /// programmatically by `Msg::OpenFileDialog` to let users upload images.
    pub file_input_ref: NodeRef,

    /// A reference to the top-level DOM node of the image dialog. Used by `open_top_sheet`
    /// and `close_top_sheet` to show or hide the dialog for image management.
    pub image_dialog_ref: NodeRef,

    /// A reference to the top-level DOM node of the PDF viewer dialog. Used to show
    /// or hide the PDF preview modal.
    pub pdf_viewer_dialog_ref: NodeRef,

    /// The data model that is persisted to the backend. It contains the `text` and a
    /// list of associated `images` (base64 encoded). It is synchronized with the `text`
    /// field and updated when images are added or removed.
    pub template: Option<Template>,

    /// When the user's cursor enters an `[img:...]` tag, this field holds the `id` of
    /// that image. It triggers the `image_dialog` to open and display the correct image.
    pub selected_image_id: Option<String>,

    /// The URL for the PDF preview, constructed in `Msg::OpenPdf`. It points to the
    /// backend endpoint and includes a cache-busting timestamp. Used as the `src` for
    /// the `<iframe>` in the `pdf_dialog`.
    pub pdf_url: Option<String>,

    /// A flag that is `true` while the PDF is being generated by the backend and the
    /// `<iframe>` is loading. It is used to display a loading indicator in the UI.
    pub pdf_loading: bool,

    /// A guard flag to ensure that one-time initialization logic in `rendered`
    /// (like loading a template or setting up event listeners) runs only once.
    pub loaded: bool,

    /// An MD5 hash of the `text` field, calculated and stored after a template is
    /// loaded or saved. It is compared against a hash of the current `text` to
    /// determine if there are unsaved changes (the "dirty" state).
    pub original_md5: Option<String>,
}

impl StaticTextComponent {
    /// Constructs a new instance with sensible defaults:
    /// - empty `text`
    /// - `history` initialized with one empty entry
    /// - `active_tab` set to `"editor"`
    /// - empty `NodeRef`s
    /// - no `template` loaded
    /// - PDF-related fields cleared
    /// - `loaded` false and `original_md5` none
    ///
    /// Guarantees a consistent initial state for the UI and undo/redo logic.
    pub fn new() -> Self {
        Self {
            text: String::new(),
            history: vec![String::new()],
            history_index: 0,
            active_tab: "editor".to_string(),
            textarea_ref: Default::default(),
            file_input_ref: Default::default(),
            image_dialog_ref: Default::default(),
            pdf_viewer_dialog_ref: Default::default(),
            template: None,
            selected_image_id: None,
            pdf_url: None,
            pdf_loading: false,
            loaded: false,
            original_md5: None,
        }
    }

    /// Adjusts the textarea CSS height to match its `scrollHeight`, producing
    /// an auto-growing textarea that avoids internal scrollbars.
    ///
    /// Behavior:
    /// - Obtains the element from `textarea_ref`.
    /// - Resets `height` to `"auto"` to recalculate `scrollHeight`.
    /// - Sets the style `height` to the computed `scrollHeight` in pixels.
    ///
    /// This method is safe: it checks presence and types before manipulating styles.
    pub fn resize_textarea(&self) {
        if let Some(textarea) = self.textarea_ref.cast::<HtmlTextAreaElement>() {
            if let Ok(html_elem) = textarea.clone().dyn_into::<HtmlElement>() {
                // Force height recalculation
                let style = html_elem.style();
                let _ = style.set_property("height", "auto");
                let scroll_height = textarea.scroll_height();
                let _ = style.set_property("height", &format!("{}px", scroll_height));
            }
        }
    }
}
