//! # Image Data Transfer Object (DTO)
//!
//! This module defines the `Image` struct, which serves as a standard representation
//! for images associated with a template throughout the application stack. It is a
//! crucial part of the `common` crate, ensuring that both the frontend and backend
//! have a consistent model for handling image data.

use serde::{Deserialize, Serialize};

/// Represents an image associated with a template.
///
/// This struct is used as a Data Transfer Object (DTO) for sending image data between
/// the frontend and the backend. It encapsulates the image's unique identifier and its
/// content, encoded in Base64.
///
/// ## Frontend Context
/// - When a user adds an image to a template in the UI, the frontend is responsible for:
///   1. Generating a unique `id` for the image (e.g., a UUID).
///   2. Reading the image file and encoding its binary data into a `base64` string.
///   3. Including a `Vec<Image>` in the `Template` object that is sent to the backend's
///      `POST /api/templates/save` endpoint.
///
/// ## Backend Context
/// - **`services::templates::save`**: The save service receives the `Vec<Image>` and
///   persists each image to the `images` table in the database. It uses the `id` as the
///   primary key and links it to the parent `template_id`.
/// - **`services::templates::get`**: When a template is requested, this service retrieves
///   all associated images from the database and includes them in the `Template` object
///   sent back to the frontend.
/// - **`services::templates::pdf`**: The PDF generation service uses the `id` to resolve
///   image tags (e.g., `[img:image_id]`) within the template text. It decodes the `base64`
///   string to get the raw image bytes, which are then processed and embedded into the
///   final PDF document.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Image {
    /// A unique identifier for the image, typically a UUID generated by the client.
    /// This ID is used as the primary key in the database and as a reference tag
    /// within the template's text content (e.g., `[img:some-unique-id]`).
    pub id: String,
    /// The complete image data encoded as a Base64 string. This format allows the
    /// binary image content to be safely embedded within a JSON payload for
    /// HTTP transport.
    pub base64: String,
}
